services:
  node:
    build: .
    image: market:v1
    restart: always
    command: [ './wait-for.sh', 'postgres:${DB_PORT}', '-t', '60', '--', 'java', '-jar', '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005', 'market-0.0.1-SNAPSHOT.jar']
    expose:
      - 8080
    ports:
# прямой доступ
      - 8000-8001:8080
# дебаггер
      - 9000-9001:5005
    environment:
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_PORT: ${DB_PORT}
      DB_HOST: postgres
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: redis
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:1.25.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - ${NGINX_PORT}:8080
    restart: always

  postgres:
    image: postgres:15.3-alpine3.18
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - ${DB_PORT}:5432

  redis:
    image: redis:7.2-rc2-alpine
    ports:
      - ${REDIS_PORT}:6379

  flyway:
    image: flyway/flyway:9.19.4-alpine
    command: -url=jdbc:postgresql://postgres:${DB_PORT}/${DB_NAME} -schemas=public -user=${DB_USER} -password=${DB_PASSWORD} -connectRetries=15 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - postgres
